### ISSUE TITLE
Make a "running commands" command

### ISSUE THREAD

**Issue by gunr2171** [gunr2171/SOCVR-Chatbot#12]
There are going to be some commands that take a while to finish (like minutes).

When a command starts, it should report the following into a queue list:

- Date/Time the command started
- The user the command was triggered for
- The name of the command

Running the command will produce a result like this:

    The following is a list of commands that I'm currently running:

    Command           For User      Started
    -----------------------------------------------------------
    Running Commands  gunr2171 (#)  4 seconds ago
	Audit Stats       rene (#)      7 minutes and 2 seconds ago
	Alive             Sam (#)       15 seconds ago

This will be a great indication to chat users that a command might be stuck or if it's still running.

**Comment by ArcticEcho** [comment]
+1 This looks like a really useful command.
