### ISSUE TITLE
Make triggers not case sensitive 

### ISSUE THREAD

**Issue by gunr2171** [gunr2171/SOCVR-Chatbot#14]
Triggers are case sensitive. Make them not.

Easiest way is to `ToLower()` both the input and the match text, or ignore case in the regex options.

**Comment by ArcticEcho** [comment]
Or use the `.ToLowerInvariant()` extension instead?

**Comment by gunr2171** [comment]
It seems I'm doing all regex testing for the triggers and commands (as I should). After I do a bit of refactoring to give triggers the same treatment I did for UserCommands I'll use `ToLowerInvariant()` on both triggers and user commands.
